---
- block:
  - name: Parse zones from output
    set_fact:
      _cs_zones: "{{ _cloudstack_zones | from_json }}"
  
  - name: Extract zones from output
    set_fact:
      cs_zones: "{{ _cs_zones | sort(attribute='name') }}"

  - name: Set the default zone
    set_fact:
      default_zone: >-
        {% for z in cs_zones %}
        {%- if z['name'] == "ch-gva-2" %}{{ loop.index }}{% endif %}
        {%- endfor %}

  - pause:
      prompt: |
        What zone should the server be located in?
          {% for z in cs_zones %}
            {{ loop.index }}. {{ z['name'] }}
            {% endfor %}

          Enter the number of your desired zone
          [{{ default_zone }}]
    register: _algo_region
  when: region is undefined
  environment:
        PYTHONPATH: "{{ cloudstack_venv }}/lib/python2.7/site-packages/"
