---
- block:
  - include_tasks: ubuntu.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include_tasks: freebsd.yml
    when: ansible_distribution == 'FreeBSD'

  - name: Gather additional facts
    import_tasks: facts.yml

  - name: Sysctl tuning
    sysctl: name="{{ item.item }}" value="{{ item.value }}"
    with_items:
      - "{{ sysctl|default([]) }}"
    tags:
      - always

  - meta: flush_handlers
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
